africaA = [['Algeria', 'DZA', 2381741.],
          ['Angola','AGO', 1246700.], 
          ['Cameroon', 'CMR', 475442.], 
          ['Central African Republic', 'CAF', 622984.], 
          ['Chad', 'TCD', 1284000.], 
          ['Congo (Democratic Republic/Kinshasa)', 'COD', 2344858.], 
          ['Egypt', 'EGY', 1002450.], 
          ['Equatorial Guinea', 'GNQ', 28051.], 
          ['Eritrea', 'ERI', 125000.], 
          ['Ivory Coast', 'CIV', 322463.], 
          ['Kenya', 'KEN', 580367.], 
          ['Rwanda', 'RWA', 26338.], 
          ['South Africa', 'ZAF', 1221037.], 
          ['Zimbabwe','ZWE', 390757.],
          ]

camericaA = [
            ['Bahamas','BHS',13943],
            ['Belize','BLZ',22966],
            ['Costa Rica','CRI',51100],
            ['Cuba','CU1', 109884],
            ['El Salvador','SLV', 21041],
            ['Guatemala','GTM', 108889],
            ['Haiti and Dominican Republic','HTI,DOM', 76421],
            ['Jamaica','JAM', 10991],
            ['Panama','PAN', 75417],
            ]

samericaA = [['Argentina','ARG',2780400 ],
            ['Brazil','BRA',8515767],
            ['Chile','CHL', 756102],
            ['Colombia','COL', 1141748],
            ['Ecuador','ECU', 276841],
            ['Peru','PER', 1285216],
            ['Uruguay','URY', 176215],
            ['Venezuela','VEN', 916445],
            ]

namericaA = [['Canada','CAN', 9984670],
            ['Mexico','MEX', 1964375],
            ['Greenland','DN1', 2166086],
            ['Us','US1', 9833517],
            ]

asiaA = [
        ['Afghanistan', 'AFG', None ],
        ['Armenia', 'ARM', None ],  
        ['Azerbaijan', 'AZE', None ],  
        ['Bangladesh', 'BGD', None ],  	
        ['Bhutan', 'BTN', None ],  	
        ['Cambodia', 'KHM', None ],  
        ['China', 'CH1', None ],  
        ['GCC States', 'KWT,SAU,BHR,QAT,OMN,ARE', None ],  	
        ['India', 'IND', None ],  	
        ['Indonesia', 'IDN', None ],  
        ['Iran', 'IRN', None ],  
        ['Iraq', 'IRQ', None ],  	
        ['Israel and Palestine',  'IS1', None ],	
        ['Japan', 'JPN', None ], 	
        ['Jordan', 'JOR', None ],	
        ['Kazakhstan', 'KA1', None ], 	
        ['Kyrgyzstan', 'KGZ', None ], 	
        ['Laos', 'LAO', None ], 	
        ['Lebanon', 'LBN', None ], 	
        ['Malaysia, Singapore, and Brunei', 'MYS,BRN,SGP', None ], 	
        ['Maldives', 'MDV', None ], 	
        ['Mongolia', 'MNG', None ], 	
        ['Myanmar', 'MMR', None ], 
        ['Nepal', 'NPL', None ], 	
        ['North Korea', 'PRK', None ], 	
        ['Pakistan', 'PAK', None ], 	
        ['Philippines', 'PHL', None ], 	
        ['South Korea', 'KOR', None ], 	
        ['Sri Lanka', 'LKA', None ], 	
        ['Syria', 'SYR', None ], 	
        ['Taiwan', 'TWN', None ], 	
        ['Tajikistan', 'TJK', None ], 	
        ['Thailand', 'THA', None ], 	
        ['Turkmenistan', 'TKM', None ], 	
        ['Uzbekistan', 'UZB', None ], 	
        ['Vietnam', 'VNM', None ], 	
        ['Yemen', 'YEM', None ] 	
       ]



europeA=[
        ['Albania', 'AL', None],	
        ['Andorra', None, None], 	
        ['Azores', 'PT', 'PT2'], 	
        ['Austria', 'AT', None], 	
        ['Belgium', 'BE', None],	
        ['Bosnia-Herzegovina', None, None],
        ['Bulgaria', 	'BG', None],
        ['Croatia', 	'HR', None],
        ['Cyprus', 	'CY', None],
        ['Czech Republic', 'CZ', None],	
        ['Denmark', 	'DK', None],
        ['Estonia', 	'EE', None],
        ['Faroe Islands', None, None],	
        ['Finland', 	'FI', None],
        ['France', 	'FR', '!=FRY'],
        ['Germany',     'DE', None],	
        ['Great Britain', 'UK', None],	
        ['Greece',	'EL', None],
        ['guernsey-jersey', None, None],	
        ['Hungary', 	'HU', None],
        ['Iceland', 	'IS', None],
        ['Ireland and Northern Ireland', 'IE', None],	
        ['Isle of Man',  None, None],
        ['Italy', 	'IT', None],
        ['Kosovo',      None, None],	
        ['Latvia', 	'LV', None],
        ['Liechtenstein', 'LI', None],	
        ['Lithuania', 	'LT', None],
        ['Luxembourg',	'LU', None],
        ['Macedonia', 	'MK', None],
        ['Malta', 	'MT', None],
        ['Monaco',      None, None],	
        ['Montenegro', 	None, None],
        ['Netherlands', 'NL', None],	
        ['Norway', 	'NO', None],
        ['Poland',      'PL', None],	
        ['Portugal', 	'PT', 'PT1'],
        ['Romania', 	'RO', None],
        ['Serbia', 	None, None],
        ['Slovakia', 	'SK', None],
        ['Slovenia', 	'SI', None],
        ['Spain', 	'ES', None],
        ['Sweden', 	'SE', None],
        ['Switzerland', 'CH', None],
        ['Turkey', 	'TR', None],
    ] 




