easteurope = [
              ['Ukraine','UKR', None ],
              ['Belarus','BLR', None ],
              ['Moldova','MDA', None ],
              ['Georgia','GEO', None ],

              ]

oceania = [
            ['Australia', 'AU1', None ], 
            ['Cook Islands', 'NZ1', 'COK'],
            ['Fiji', 'FJI', None ], 
            ['Ile de Clipperton', 'FR1', 'CLP'], 
            ['Kiribati', 'KIR', None],
            ['Marshall Islands', 'MHL', None],
            ['Micronesia', 'FSM', None], 
            ['Nauru', 'NRU', None],
            ['New Caledonia', 'FR1','NCL'],
            ['New Zealand', 'NZ1', None],
            ['Niue', 'NZ1', 'NIU'],
            ['Palau', 'PLW', None],
            ['Papua New Guinea', 'PNG', None],
            ['Pitcairn Islands','GB1' , 'PCN'], 
            ['polynesie-francaise','FR1' , 'PYF'],
            ['Samoa', 'WSM', None],
            ['Solomon Islands', 'SLB', None],
            ['Tokelau', 'NZ1', None], 
            ['Tonga', 'TON', None],
            ['Tuvalu', 'TUV', None],
            ['Vanuatu', 'VUT', None], 
            ['Wallis et Futuna', 'FR1', 'WLF'], 
        ]

russia = [['Russia','RUS', None ],]

africa = [['Algeria', 'DZA', None],
          ['Angola','AGO', None], 
          ['Benin', 'BEN', None],
          ['Botswana', 'BWA', None],
          ['Burkina Faso', 'BFA', None], 
          ['Burundi', 'BDI', None], 
          ['Cameroon', 'CMR', None], 
          ['Canary Islands', 'ESP', None], 
          ['Cape Verde', 'CPV', None], 
          ['Central African Republic', 'CAF', None], 
          ['Chad', 'TCD', None], 
          ['Comores', 'COM', None], 
          ['Congo (Republic/Brazzaville)', 'COG', None], 
          ['Congo (Democratic Republic/Kinshasa)', 'COD', None], 
          ['Djibouti', 'DJI', None], 
          ['Egypt', 'EGY', None], 
          ['Equatorial Guinea', 'GNQ', None], 
          ['Eritrea', 'ERI', None], 
          ['Ethiopia', 'ETH', None], 
          ['Gabon', 'GAB', None], 
          ['Ghana', 'GHA', None], 
          ['Guinea', 'GIN', None], 
          ['Guinea-Bissau', 'GNB', None], 
          ['Ivory Coast', 'CIV', None], 
          ['Kenya', 'KEN', None], 
          ['Lesotho', 'LSO', None], 
          ['Liberia', 'LBR', None], 
          ['Libya', 'LBY', None], 
          ['Madagascar', 'MDG', None], 
          ['Malawi', 'MWI', None], 
          ['Mali', 'MLI', None], 
          ['Mauritania', 'MRT', None], 
          ['Mauritius','MUS',None], 
          ['Morocco', 'MAR,SAH', None], 
          ['Mozambique', 'MOZ', None], 
          ['Namibia', 'NAM', None], 
          ['Niger', 'NER', None], 
          ['Nigeria', 'NGA', None], 
          ['Rwanda', 'RWA', None], 
          ['Saint Helena, Ascension, and Tristan da Cunha', None, None], 
          ['Sao Tome and Principe', 'STP', None], 
          ['Senegal and Gambia', 'GMB,SEN', None], 
          ['Seychelles', 'SYC', None], 
          ['Sierra Leone', 'SLE', None], 
          ['Somalia', 'SOM,SOL', None], 
          ['South Africa', 'ZAF', None], 
          ['South Sudan', 'SDS', None], 
          ['Sudan', 'SDN,BRT', None], 
          ['Swaziland', 'SWZ', None], 
          ['Tanzania', 'TZA', None], 
          ['Togo', 'TGO', None], 
          ['Tunisia', 'TUN', None], 
          ['Uganda', 'UGA', None], 
          ['Zambia', 'ZMB', None], 
          ['Zimbabwe','ZWE', None],
          ['Mayotte','FR1', None],
          ['Reunion','FR1', None],
          ]

camerica = [['Anguilla',None,None],
            ['Antigua and Barbuda','ATG',None],
            ['Aruba','NL1',None],
            ['Bahamas','BHS',None],
            ['Barbados','BRB',None],
            ['British Virgin Islands','GB1','VGB'],
            ['Belize','BLZ',None],
            ['Cayman Islands','GB1','CYM'],
            ['Costa Rica','CRI',None],
            ['Curacao','NL1','CUW'],
            ['Dominica','DMA',None],
            ['Grenada','GRD',None],
            ['Cuba','CU1', None],
            ['El Salvador','SLV', None],
            ['Guatemala','GTM', None],
            ['Haiti and Dominican Republic','HTI,DOM', None],
            ['Honduras','HND', None],
            ['Jamaica','JAM', None],
            ['Montserrat','BG1','MSR'],
            ['Nicaragua','NIC', None],
            ['Panama','PAN', None],
            ['Puerto Rico','US1','PRI'],
            ['Saint Barthelemy','FR1','BLM'],
            ['Saint Kitts and Nevis','KNA',None],
            ['Saint Lucia','LCA',None],
            ['Saint Martin','FR1','MAF'],
            ['Saint Vincent and the Grenadines','VCT',None],
            ['Sint Maarten','NL1','SXM'],
            ['Trinidad and Tobago','TTO',None],
            ['Turks and Caicos Islands','GB1','TCA'],
            ['United States Virgin Islands','US1','VIR'],
            ['Guadeloupe','FR1', None],
            ['Martinique','FR1', None],
            ]

samerica = [['Argentina','ARG',None],
            ['Bolivia','BOL',None],
            ['Brazil','BRA',None],
            ['Chile','CHL', None],
            ['Colombia','COL', None],
            ['Ecuador','ECU', None],
            ['Guyana','GUY', None],
            ['Paraguay','PRY', None],
            ['Peru','PER', None],
            ['Suriname','SUR', None],
            ['Uruguay','URY', None],
            ['Venezuela','VEN', None],
            ['Guyane','FR1', None],
            ]

namerica = [['Canada','CAN',None],
            ['Mexico','MEX',None],
            ['Greenland','DN1',None],
            ['Us','US1', None],
            ]

namerica2 = [['Canada','CAN',None],
            ]

asia = [
        ['Afghanistan', 'AFG', None ],
        ['Armenia', 'ARM', None ],  
        ['Azerbaijan', 'AZE', None ],  
        ['Bangladesh', 'BGD', None ],  	
        ['Bhutan', 'BTN', None ],  	
        ['Cambodia', 'KHM', None ],  
        ['China', 'CH1', None ],  
        ['GCC States', 'KWT,SAU,BHR,QAT,OMN,ARE', None ],  	
        ['India', 'IND', None ],  	
        ['Indonesia', 'IDN', None ],  
        ['Iran', 'IRN', None ],  
        ['Iraq', 'IRQ', None ],  	
        ['Israel and Palestine',  'IS1', None ],	
        ['Japan', 'JPN', None ], 	
        ['Jordan', 'JOR', None ],	
        ['Kazakhstan', 'KA1', None ], 	
        ['Kyrgyzstan', 'KGZ', None ], 	
        ['Laos', 'LAO', None ], 	
        ['Lebanon', 'LBN', None ], 	
        ['Malaysia, Singapore, and Brunei', 'MYS,BRN,SGP', None ], 	
        ['Maldives', 'MDV', None ], 	
        ['Mongolia', 'MNG', None ], 	
        ['Myanmar', 'MMR', None ], 
        ['Nepal', 'NPL', None ], 	
        ['North Korea', 'PRK', None ], 	
        ['Pakistan', 'PAK', None ], 	
        ['Philippines', 'PHL', None ], 	
        ['South Korea', 'KOR', None ], 	
        ['Sri Lanka', 'LKA', None ], 	
        ['Syria', 'SYR', None ], 	
        ['Taiwan', 'TWN', None ], 	
        ['Tajikistan', 'TJK', None ], 	
        ['Thailand', 'THA', None ], 	
        ['Turkmenistan', 'TKM', None ], 	
        ['Uzbekistan', 'UZB', None ], 	
        ['Vietnam', 'VNM', None ], 	
        ['Yemen', 'YEM', None ] 	
       ]



europe=[
        ['Albania', 'AL', None],	
        ['Andorra', None, None], 	
        ['Azores', 'PT', 'PT2'], 	
        ['Austria', 'AT', None], 	
        ['Belgium', 'BE', None],	
        ['Bosnia-Herzegovina', None, None],
        ['Bulgaria', 	'BG', None],
        ['Croatia', 	'HR', None],
        ['Cyprus', 	'CY', None],
        ['Czech Republic', 'CZ', None],	
        ['Denmark', 	'DK', None],
        ['Estonia', 	'EE', None],
        ['Faroe Islands', None, None],	
        ['Finland', 	'FI', None],
        ['France', 	'FR', '!=FRY'],
        ['Germany',     'DE', None],	
        ['Great Britain', 'UK', None],	
        ['Greece',	'EL', None],
        ['guernsey-jersey', None, None],	
        ['Hungary', 	'HU', None],
        ['Iceland', 	'IS', None],
        ['Ireland and Northern Ireland', 'IE', None],	
        ['Isle of Man',  None, None],
        ['Italy', 	'IT', None],
        ['Kosovo',      None, None],	
        ['Latvia', 	'LV', None],
        ['Liechtenstein', 'LI', None],	
        ['Lithuania', 	'LT', None],
        ['Luxembourg',	'LU', None],
        ['Macedonia', 	'MK', None],
        ['Malta', 	'MT', None],
        ['Monaco',      None, None],	
        ['Montenegro', 	None, None],
        ['Netherlands', 'NL', None],	
        ['Norway', 	'NO', None],
        ['Poland',      'PL', None],	
        ['Portugal', 	'PT', 'PT1'],
        ['Romania', 	'RO', None],
        ['Serbia', 	None, None],
        ['Slovakia', 	'SK', None],
        ['Slovenia', 	'SI', None],
        ['Spain', 	'ES', None],
        ['Sweden', 	'SE', None],
        ['Switzerland', 'CH', None],
        ['Turkey', 	'TR', None],
    ] 




