countries=[
        ['Albania', 'AL', None],	
        ['Andorra', None, None], 	
        ['Azores', 'PT', 'PT2'], 	
        ['Austria', 'AT', None], 	
        ['Belgium', 'BE', None],	
        ['Bosnia-Herzegovina', None, None],
        ['Bulgaria', 	'BG', None],
        ['Croatia', 	'HR', None],
        ['Cyprus', 	'CY', None],
        ['Czech Republic', 'CZ', None],	
        ['Denmark', 	'DK', None],
        ['Estonia', 	'EE', None],
        ['Faroe Islands', None, None],	
        ['Finland', 	'FI', None],
        ['France', 	'FR', '!=FRY'],
        ['Germany',     'DE', None],	
        ['Great Britain', 'UK', None],	
        ['Greece',	'EL', None],
        ['guernsey-jersey', None, None],	
        ['Hungary', 	'HU', None],
        ['Iceland', 	'IS', None],
        ['Ireland and Northern Ireland', 'IE', None],	
        ['Isle of Man',  None, None],
        ['Italy', 	'IT', None],
        ['Kosovo',      None, None],	
        ['Latvia', 	'LV', None],
        ['Liechtenstein', 'LI', None],	
        ['Lithuania', 	'LT', None],
        ['Luxembourg',	'LU', None],
        ['Macedonia', 	'MK', None],
        ['Malta', 	'MT', None],
        ['Monaco',      None, None],	
        ['Montenegro', 	None, None],
        ['Netherlands', 'NL', None],	
        ['Norway', 	'NO', None],
        ['Poland',      'PL', None],	
        ['Portugal', 	'PT', 'PT1'],
        ['Romania', 	'RO', None],
        ['Serbia', 	None, None],
        ['Slovakia', 	'SK', None],
        ['Slovenia', 	'SI', None],
        ['Spain', 	'ES', None],
        ['Sweden', 	'SE', None],
        ['Switzerland', 'CH', None],
        ['Turkey', 	'TR', None],
    ] 




