namerica = [['Canada','CAN',None],
            ['Mexico','MEX',None],
            ['Greenland','DN1',None],
            ['Us','US1', None],
            ]

asia = [
        ['Afghanistan', 'AFG', None ],
        ['Armenia', 'ARM', None ],  
        ['Azerbaijan', 'AZE', None ],  
        ['Bangladesh', 'BGD', None ],  	
        ['Bhutan', 'BTN', None ],  	
        ['Cambodia', 'KHM', None ],  
        ['China', 'CH1', None ],  
        ['GCC States', 'KWT,SAU,BHR,QAT,OMN,ARE', None ],  	
        ['India', 'IND', None ],  	
        ['Indonesia', 'IDN', None ],  
        ['Iran', 'IRN', None ],  
        ['Iraq', 'IRQ', None ],  	
        ['Israel and Palestine',  'IS1', None ],	
        ['Japan', 'JPN', None ], 	
        ['Jordan', 'JOR', None ],	
        ['Kazakhstan', 'KA1', None ], 	
        ['Kyrgyzstan', 'KGZ', None ], 	
        ['Laos', 'LAO', None ], 	
        ['Lebanon', 'LBN', None ], 	
        ['Malaysia, Singapore, and Brunei', 'MYS,BRN,SGP', None ], 	
        ['Maldives', 'MDV', None ], 	
        ['Mongolia', 'MNG', None ], 	
        ['Myanmar', 'MMR', None ], 
        ['Nepal', 'NPL', None ], 	
        ['North Korea', 'PRK', None ], 	
        ['Pakistan', 'PAK', None ], 	
        ['Philippines', 'PHL', None ], 	
        ['South Korea', 'KOR', None ], 	
        ['Sri Lanka', 'LKA', None ], 	
        ['Syria', 'SYR', None ], 	
        ['Taiwan', 'TWN', None ], 	
        ['Tajikistan', 'TJK', None ], 	
        ['Thailand', 'THA', None ], 	
        ['Turkmenistan', 'TKM', None ], 	
        ['Uzbekistan', 'UZB', None ], 	
        ['Vietnam', 'VNM', None ], 	
        ['Yemen', 'YEM', None ] 	
       ]



europe=[
        ['Albania', 'AL', None],	
        ['Andorra', None, None], 	
        ['Azores', 'PT', 'PT2'], 	
        ['Austria', 'AT', None], 	
        ['Belgium', 'BE', None],	
        ['Bosnia-Herzegovina', None, None],
        ['Bulgaria', 	'BG', None],
        ['Croatia', 	'HR', None],
        ['Cyprus', 	'CY', None],
        ['Czech Republic', 'CZ', None],	
        ['Denmark', 	'DK', None],
        ['Estonia', 	'EE', None],
        ['Faroe Islands', None, None],	
        ['Finland', 	'FI', None],
        ['France', 	'FR', '!=FRY'],
        ['Germany',     'DE', None],	
        ['Great Britain', 'UK', None],	
        ['Greece',	'EL', None],
        ['guernsey-jersey', None, None],	
        ['Hungary', 	'HU', None],
        ['Iceland', 	'IS', None],
        ['Ireland and Northern Ireland', 'IE', None],	
        ['Isle of Man',  None, None],
        ['Italy', 	'IT', None],
        ['Kosovo',      None, None],	
        ['Latvia', 	'LV', None],
        ['Liechtenstein', 'LI', None],	
        ['Lithuania', 	'LT', None],
        ['Luxembourg',	'LU', None],
        ['Macedonia', 	'MK', None],
        ['Malta', 	'MT', None],
        ['Monaco',      None, None],	
        ['Montenegro', 	None, None],
        ['Netherlands', 'NL', None],	
        ['Norway', 	'NO', None],
        ['Poland',      'PL', None],	
        ['Portugal', 	'PT', 'PT1'],
        ['Romania', 	'RO', None],
        ['Serbia', 	None, None],
        ['Slovakia', 	'SK', None],
        ['Slovenia', 	'SI', None],
        ['Spain', 	'ES', None],
        ['Sweden', 	'SE', None],
        ['Switzerland', 'CH', None],
        ['Turkey', 	'TR', None],
    ] 




